### ISSUE TITLE
Need 3.6 version of shield-addon-mongodb-boshrelease

### ISSUE THREAD

**Issue by Alexvianet** [shieldproject/shield-addon-mongodb-boshrelease#1]
mongodump 3.5.x incompatible with mongodb 3.6.x #37
I get:
2018-11-26T02:00:01.912+0000	Failed: error counting admin.system.keys: not authorized on admin to execute command { count: "system.keys", query: {}, $readPreference: { mode: "secondaryPreferred" }, $db: "admin" }
Unable to exec '/var/vcap/packages/shield-addon-mongo-tools-3.4/bin/mongodump': exit status 1

https://github.com/stefanprodan/mgob/issues/37 - details

https://github.com/mongodb/mongo-tools/archive/r3.6.9.tar.gz

**Comment by Alexvianet** [comment]
@jhunt  help please

**Comment by jhunt** [comment]
Sorry, wasn't watching this repo for some reason...

**Comment by Alexvianet** [comment]
thanks for replay

**Comment by Alexvianet** [comment]
@jhunt any updates?

**Comment by jhunt** [comment]
It's first on my list this morning!

**Comment by jhunt** [comment]
Had some issues with CI/CD (like always 😁); working through a shipit as I write this.

**Comment by jhunt** [comment]
After much consternation from Concourse, v1.0.1 of this addon is released, with MongoDB 3.6.9.  Can you take that for a spin and see if it works for you?

**Comment by Alexvianet** [comment]
i ll do it tomorrow

**Comment by jhunt** [comment]
Any updates, @Alexvianet ?

**Comment by Alexvianet** [comment]
oh sorry all works now thanks

**Comment by jhunt** [comment]
No worries.  Glad it worked out!
