### ISSUE TITLE
Add support for MongoDB 4.0 and 4.2

### ISSUE THREAD

**Issue by mordax7** [shieldproject/shield-addon-mongodb-boshrelease#2]
Hello,

could we get support for the newer MongoDB releases v4.0 and v4.2?

Thanks.

**Comment by jhunt** [comment]
Sure!

It looks like 4.0.x is distributed as a generic Linux tarball (https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-4.0.13.tgz) but 4.2.1 is not.  It might be a bit of a slog to get that version extracted.  I'll put in a separate ticket for the 4.x upgrade.
